
server:
  port: 9090

# AWS Config details
aws:
  region: ap-south-1
  credentials:
    accessKey: 
    secretKey: 
  s3:
    bucket: s3awstestbucket1

logging:
  level:
    root: INFO
    com.example.aws: DEBUG 
