
server:
  port: 9095

# AWS Config details
aws:
  region: ap-south-1
  credentials:
    accessKey: 
    secretKey: 
  s3:
    bucket: s3awstestbucket1 
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always